
FROM ubuntu:14.04
MAINTAINER      Satish <satish@healthseq.com>
# Use this to use BWA. 

RUN apt-get update && \
    apt-get -y install gcc mono-mcs zlib1g-dev make wget git -y -f && \


wget http://sourceforge.net/projects/bio-bwa/files/bwa-0.7.12.tar.bz2 && \
mkdir /dnasoft && \
mv /bwa-0.7.12.tar.bz2 /dnasoft/bwa-0.7.12.tar.bz2 && \
cd /dnasoft && \
tar -xvf /dnasoft/bwa-0.7.12.tar.bz2 && \
cd /dnasoft/bwa-0.7.12 && \
make && \

cd /dnasoft && \

# Download your sequence below
wget https://s3.amazonaws.com/data-upload-satish/human_g1k_v37_trimmed.fasta.gz && \
gunzip human_g1k_v37_trimmed.fasta.gz && \


cd /dnasoft/bwa-0.7.12 && \

#Run BWA commands
./bwa index /dnasoft/human_g1k_v37_trimmed.fasta
