# Samtools Docker Container
FROM ubuntu:14.04
MAINTAINER      Satish <satish@healthseq.com>

# Install packages required by python , gcc, make , wget etc
 RUN  apt-get update && \
      apt-get install wget zlib1g-dev make libncurses-dev -y

# Download samtools in /dnasoft and install
RUN wget https://github.com/samtools/samtools/releases/download/1.2/samtools-1.2.tar.bz2 --no-check-certificate &&     mkdir /dnasoft &&     mv /samtools-1.2.tar.bz2 /dnasoft/samtools-1.2.tar.bz2 &&     cd /dnasoft &&     tar -xvf /dnasoft/samtools-1.2.tar.bz2 &&     cd /dnasoft/samtools-1.2 &&         make &&         make install &&         make prefix=/dnapipeline

# Clean up
RUN rm -rf /dnasoft/samtools-1.2.tar.bz2

# Set PATH
ENV PATH /dnasoft/samtools-1.2:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games

# Set working directory for the container
WORKDIR /dnasoft/samtools-1.2/

