#!/usr/bin/env python

# Generated by mock-builder

from flask import Flask, request

app = Flask(__name__)

@app.route("/_uuids", methods=["GET"])
def get__uuids():
    return ('''{"uuids":["b0144f1805876f2b903339021d014c93"]}''', 200, {'Server': 'CouchDB/1.0.1 (Erlang OTP/R14B)', 'Pragma': 'no-cache', 'Expires': 'Fri, 01 Jan 1990 00:00:00 GMT', 'ETag': '"6HYGXY94MRJVTU4OTZM7VA65U"', 'Date': 'Mon, 28 Oct 2013 23:58:27 GMT', 'Content-Type': 'application/json', 'Content-Length': '47', 'Cache-Control': 'must-revalidate, no-cache'})

@app.route("/test", methods=["HEAD"])
def head_test():
    return ('''''', 200, {'Server': 'CouchDB/1.0.1 (Erlang OTP/R14B)', 'Date': 'Mon, 28 Oct 2013 23:58:27 GMT', 'Content-Type': 'application/json', 'Content-Length': '216', 'Cache-Control': 'must-revalidate'})

@app.route("/test/<uuid0>", methods=["PUT"])
def put_test__uuid0_(uuid0):
    return ('''{"ok":true,"id":"b0144f1805876f2b903339021d014c93","rev":"1-9e6edc4815ee6350b93db6f2afc488f0"}
''', 201, {'Server': 'CouchDB/1.0.1 (Erlang OTP/R14B)', 'Location': 'http://localhost:5984/test/b0144f1805876f2b903339021d014c93', 'Etag': '"1-9e6edc4815ee6350b93db6f2afc488f0"', 'Date': 'Mon, 28 Oct 2013 23:58:27 GMT', 'Content-Type': 'application/json', 'Content-Length': '95', 'Cache-Control': 'must-revalidate'})

if __name__ == "__main__":
    app.run(host="127.1", debug=True, port=5984)
